language: node_js
node_js:
  - 8
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - semantic-release pre
  - npm publish
  - semantic-release post
notifications:
  email: false
sudo: false
